version: '3.8'
services:
  gatsby:
    build:
      context: ./gatsby-test
      dockerfile: Dockerfile
    container_name: gatsby
    depends_on:
      - strapi
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped

  strapi:
    image: strapi/strapi:latest
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./strapi:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
